# -*- coding: utf-8 -*-
"""Copy of smart agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EA0ryx3PeK_8CK_5nV6dmKhh9d1mN1vd
"""

!pip install streamlit openai sentence-transformers faiss-cpu numpy

import streamlit as st
import os
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from openai import OpenAI

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Smart RAG Agent",
    page_icon="🧠",
    layout="wide"
)

# --- CUSTOM CSS FOR POLISH ---
st.markdown("""
<style>
    .stChatInput {position: fixed; bottom: 30px;}
    .block-container {padding-top: 2rem;}
    h1 {color: #2e86c1;}
    .reportview-container .main .block-container{
        max-width: 1000px;
    }
</style>
""", unsafe_allow_html=True)

# --- 1. CACHED RESOURCE LOADING (Performance) ---
@st.cache_resource
def load_embedding_model():
    """Loads the model once and keeps it in memory."""
    return SentenceTransformer("all-MiniLM-L6-v2")

try:
    embedding_model = load_embedding_model()
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

# --- 2. SIDEBAR: SETUP & KNOWLEDGE BASE ---
with st.sidebar:
    st.header("⚙️ Configuration")

    # Secure API Key Input
    api_key = st.text_input("OpenAI API Key", type="password", help="Enter your key here to activate the agent.")
    if api_key:
        os.environ["OPENAI_API_KEY"] = api_key
        client = OpenAI()
    else:
        st.warning("⚠️ Please enter an API Key to proceed.")
        client = None

    st.divider()

    st.subheader("📚 Knowledge Base")
    st.info("Edit the documents below to teach the agent new facts!")

    # Default content from your notebook
    default_text = """Artificial intelligence agents can be reactive, goal-based, utility-based, or learning agents.
Transformers use self-attention to capture relationships between tokens.
Recurrent Neural Networks suffer from vanishing gradients, especially in long sequences.
LSTMs and GRUs are variants of RNNs designed to better capture long-term dependencies.
BERT is a bidirectional transformer encoder pre-trained using masked language modeling.
GPT models are decoder-based transformers designed for autoregressive generation.
Sequence-to-sequence models are widely used in machine translation tasks.
Information retrieval can be enhanced using dense embeddings such as SBERT.
The midterm exam for this class covers arrays, linked lists, stacks, and queues.
The professor's favorite color is Deep Blue, but he hates the color yellow."""

    kb_input = st.text_area("Documents (One per line)", value=default_text, height=300)

    # Button to rebuild index
    if st.button("🔄 Rebuild Brain (Index)", type="primary"):
        with st.spinner("Indexing documents..."):
            documents = [line.strip() for line in kb_input.split('\n') if line.strip()]

            if documents:
                # Create Embeddings
                embeddings = embedding_model.encode(documents)
                dimension = embeddings.shape[1]

                # Create FAISS Index
                index = faiss.IndexFlatL2(dimension)
                index.add(np.array(embeddings))

                # Save to session state
                st.session_state['index'] = index
                st.session_state['documents'] = documents
                st.success(f"Indexed {len(documents)} documents!")
            else:
                st.error("Knowledge base is empty.")

# --- 3. MAIN APP LOGIC ---

st.title("🧠 Smart QA Agent")
st.caption("A Retrieval-Augmented Generation (RAG) System Demo")

# Initialize chat history if not present
if "messages" not in st.session_state:
    st.session_state["messages"] = [{"role": "assistant", "content": "Hello! Ask me anything about the Knowledge Base defined in the sidebar."}]

# Display chat messages
for msg in st.session_state.messages:
    if msg["role"] != "system": # Don't show system prompts
        st.chat_message(msg["role"]).write(msg["content"])

# --- 4. SEARCH & GENERATION FUNCTIONS ---

def retrieve_docs(query, k=2):
    if 'index' not in st.session_state:
        return []

    query_vec = embedding_model.encode([query])
    distances, idx = st.session_state['index'].search(np.array(query_vec), k)

    # Handle case where index might be empty or invalid
    results = []
    for i in idx[0]:
        if 0 <= i < len(st.session_state['documents']):
            results.append(st.session_state['documents'][i])
    return results

def generate_answers(query, retrieved_context):
    context_str = "\n".join(retrieved_context)

    # 1. RAG Prompt
    rag_prompt = f"""
    You are a helpful teaching assistant.
    Use ONLY the context below to answer the question. If the answer isn't in the context, say "I don't know based on the provided documents."

    Context:
    {context_str}

    Question: {query}
    """

    # 2. Pure GPT Prompt (for comparison)
    base_prompt = f"Answer the following question to the best of your ability: {query}"

    rag_response = "Error: Client not initialized"
    base_response = "Error: Client not initialized"

    if client:
        # Get RAG Answer
        r1 = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": rag_prompt}],
            temperature=0.3
        )
        rag_response = r1.choices[0].message.content

        # Get Base Answer
        r2 = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": base_prompt}],
            temperature=0.3
        )
        base_response = r2.choices[0].message.content

    return rag_response, base_response

# --- 5. CHAT INPUT HANDLER ---
if prompt := st.chat_input():
    if not client:
        st.error("Please enter your API Key in the sidebar first.")
    elif 'index' not in st.session_state:
        st.error("Please click 'Build Brain (Index)' in the sidebar first.")
    else:
        # User Message
        st.session_state.messages.append({"role": "user", "content": prompt})
        st.chat_message("user").write(prompt)

        # Processing
        with st.spinner("Thinking..."):
            # 1. Retrieve
            retrieved_docs = retrieve_docs(prompt)

            # 2. Generate
            rag_ans, base_ans = generate_answers(prompt, retrieved_docs)

            # 3. Format Output

            # Create a visual container for the answer
            with st.chat_message("assistant"):

                # A. Show what the AI "read" (The Retrieval Part)
                with st.expander("🔍 **Step 1: Retrieval (What I read)**", expanded=False):
                    if retrieved_docs:
                        for idx, doc in enumerate(retrieved_docs):
                            st.info(f"**Doc {idx+1}:** {doc}")
                    else:
                        st.warning("No relevant documents found.")

                # B. Side-by-Side Comparison
                st.markdown("#### **Step 2: Answer Comparison**")
                col1, col2 = st.columns(2)

                with col1:
                    st.success("**✅ RAG Agent (Context-Aware)**")
                    st.write(rag_ans)

                with col2:
                    st.warning("**🤖 Standard GPT (General Knowledge)**")
                    st.write(base_ans)

            # Save assistant response to history (we only save the RAG answer text for simplicity in history)
            st.session_state.messages.append({"role": "assistant", "content": rag_ans})